# WebSocket Server - Isolated Setup
# Instance: odin-ws-go (dedicated e2-standard-2)
# Purpose: Handle WebSocket connections with full observability (logs + metrics)
#
# CONFIGURATION:
#   All settings are in .env.production file (documented with formulas/rationale)
#   Override for local testing: Create .env.production.local (gitignored)
#   Override at deployment: Set environment variables (takes precedence over .env)
#
# DEPLOYMENT:
#   1. Set BACKEND_INTERNAL_IP environment variable (required for NATS connection)
#   2. Run: export BACKEND_INTERNAL_IP=10.128.0.2 && docker-compose up -d
#
# DOCKER RESOURCE LIMITS:
#   - Must match WS_CPU_LIMIT and WS_MEMORY_LIMIT in .env.production
#   - CPU: 1.9 cores (leaves 0.1 for Promtail)
#   - Memory: 7168M (leaves ~1GB for system + Promtail from 8GB total)

services:
  ws-go:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: odin-ws-go
    ports:
      - "0.0.0.0:3004:3002"
    command:
      - "./odin-ws-server"
    # Load configuration from .env.production file
    # All environment variables are documented there with formulas and rationale
    # To override: Create .env.production.local (gitignored) or set ENV vars at runtime
    env_file:
      - .env.production
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.9"
          memory: 7168M
    ulimits:
      nofile:
        soft: 200000
        hard: 200000

  promtail:
    image: grafana/promtail:3.3.2
    container_name: odin-ws-promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail-config.yml
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 256M
