# WebSocket Server - Isolated Setup
# Instance: odin-ws-go (dedicated e2-standard-2)
# Purpose: Handle WebSocket connections with full observability (logs + metrics)
#
# This compose file is templated. Before deployment, substitute:
#   ${BACKEND_INTERNAL_IP} - Internal IP of backend instance running NATS/Loki
#
# Example:
#   export BACKEND_INTERNAL_IP=10.128.0.2
#   envsubst < docker-compose.yml | docker compose -f - up -d

services:
  ws-go:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: odin-ws-go
    ports:
      - "0.0.0.0:3004:3002"
    command:
      - "./odin-ws-server"
      - "-addr"
      - ":3002"
      - "-nats"
      - "nats://${BACKEND_INTERNAL_IP}:4222"
    environment:
      # Resource limits (e2-standard-2: 2 vCPU, 8GB RAM)
      # Allocation: 1.9 CPU, 7GB (leaves 0.1 CPU + 256M for Promtail + 768M system)
      - WS_CPU_LIMIT=1.9
      - WS_MEMORY_LIMIT=7516192768 # 7 GB in bytes (7168 MB)

      # Capacity: 10,000 connections (realistic with 0.7MB per conn)
      - WS_MAX_CONNECTIONS=10000

      # Worker pool sizing
      # Formula: max(32, connections/40) = max(32, 10000/40) = 250 → 256 (power of 2)
      # Load per worker: (10000 × 12) / 256 = 468 msg/sec per worker
      - WS_WORKER_POOL_SIZE=256
      - WS_WORKER_QUEUE_SIZE=25600 # 100x workers

      # Rate limiting (safety valves)
      # With filtering: ~1,210 avg subscribers per message
      # 12 msg/sec × 1,210 = 14,520 writes/sec
      - WS_MAX_NATS_RATE=1000
      - WS_MAX_BROADCAST_RATE=1000

      # Goroutine limit
      # Formula: ((10000 × 2) + 256 + 13) × 1.2 = 24,323
      # Rounded: 25,000
      - WS_MAX_GOROUTINES=25000

      # Safety thresholds
      - WS_CPU_REJECT_THRESHOLD=75.0
      - WS_CPU_PAUSE_THRESHOLD=80.0

      # Logging
      - LOG_LEVEL=info
      - LOG_FORMAT=json

    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.9"
          memory: 7168M
    ulimits:
      nofile:
        soft: 200000
        hard: 200000

  promtail:
    image: grafana/promtail:3.3.2
    container_name: odin-ws-promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail-config.yml
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 256M
