# Promtail Configuration - ws-go Instance
# Ships logs from ws-go container to Loki on backend instance

server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  # Point to Loki on backend instance (internal IP)
  # ${BACKEND_INTERNAL_IP} will be substituted during deployment
  - url: http://${BACKEND_INTERNAL_IP}:3100/loki/api/v1/push

scrape_configs:
  # Scrape logs from local Docker containers
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Only scrape odin-ws-go container
      - source_labels: ['__meta_docker_container_name']
        regex: '/(odin-ws-go)'
        action: keep

      # Extract container name
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container_name'

      # Extract container ID
      - source_labels: ['__meta_docker_container_id']
        regex: '(.*)'
        target_label: 'container_id'

      # Extract image name
      - source_labels: ['__meta_docker_container_image']
        regex: '(.*)'
        target_label: 'image'

      # Add service label
      - source_labels: ['container_name']
        regex: 'odin-ws-go'
        target_label: 'service'
        replacement: 'websocket-go'

      # Add instance label
      - target_label: 'instance'
        replacement: 'odin-ws-go'

      # Add environment label
      - target_label: 'environment'
        replacement: 'docker'

      # Add job label
      - target_label: 'job'
        replacement: 'docker-containers'

    pipeline_stages:
      # Parse timestamp if present
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})'
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05'
          fallback_formats:
            - RFC3339
            - RFC3339Nano

      # Extract log level
      - regex:
          expression: '(?i)(?P<level>(DEBUG|INFO|WARN|WARNING|ERROR|FATAL|TRACE))'
      - labels:
          level:

      # Extract message content
      - regex:
          expression: '(?P<message>.*)'

      # Add labels for specific patterns
      - match:
          selector: '{service="websocket-go"}'
          stages:
            - regex:
                expression: '(?i)(broadcast|connection|message|client|nats)'
            - labels:
                event_type:
