version: "3.8"

services:
  nats:
    image: nats:2.10-alpine
    container_name: odin-nats
    ports:
      - "4222:4222" # Client connections
      - "8222:8222" # HTTP monitoring
      - "6222:6222" # Cluster routing
    command:
      - "--jetstream"
      - "--store_dir=/data"
      - "--http_port=8222"
    volumes:
      - nats_data:/data
    networks:
      - odin-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8222/healthz",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    # Resource limits for NATS
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M
        reservations:
          cpus: "0.5"
          memory: 128M

  ws-go-2:
    build:
      context: ./go-server-2
      dockerfile: Dockerfile
    container_name: odin-ws-go-2
    ports:
      - "3004:3002" # WebSocket port
      - "9092:3002" # Metrics endpoint (shares same port as WebSocket)
    command:
      ["./odin-ws-server-2", "-addr", ":3002", "-nats", "nats://nats:4222"]
    networks:
      - odin-network
    depends_on:
      nats:
        condition: service_healthy
    restart: unless-stopped
    # IDENTICAL RESOURCE CONSTRAINTS
    deploy:
      resources:
        limits:
          cpus: "2.0" # Max 2 CPU cores
          memory: 512M # Max 512MB RAM
        reservations:
          cpus: "1.0" # Guaranteed 1 CPU core
          memory: 256M # Guaranteed 256MB RAM
    mem_swappiness: 10 # Reduce swap usage
    pids_limit: 1000 # Increased for more goroutines
    ulimits:
      nofile:
        soft: 200000 # Support 20k+ connections with available RAM
        hard: 200000
      nproc:
        soft: 32768 # More threads
        hard: 32768
    blkio_config:
      weight: 500 # Disk I/O weight (100-1000)

  ws-go-3:
    build:
      context: ./go-server-3
      dockerfile: Dockerfile
    container_name: odin-ws-go-3
    ports:
      - "3005:8082" # External 3005 maps to Go-3 server
      - "9096:9095" # Metrics endpoint for Go-3 server
    environment:
      - ODIN_SERVER_HOST=0.0.0.0
      - ODIN_SERVER_PORT=8082
      - ODIN_METRICS_LISTEN_ADDR=:9095
      - ODIN_WEBSOCKET_PATH=/ws
    command:
      ["./odin-ws-server-3"]
    networks:
      - odin-network
    depends_on:
      nats:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 512M
        reservations:
          cpus: "1.0"
          memory: 256M
    mem_swappiness: 10
    pids_limit: 2000
    ulimits:
      nofile:
        soft: 400000
        hard: 400000
      nproc:
        soft: 65536
        hard: 65536
    blkio_config:
      weight: 700

  ws-node:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: odin-ws-node
    ports:
      - "3001:3001" # WebSocket port
    environment:
      - NATS_URL=nats://nats:4222
      - PORT=3001
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=400 # Limit Node.js heap
    networks:
      - odin-network
    depends_on:
      nats:
        condition: service_healthy
    restart: unless-stopped
    # IDENTICAL RESOURCE CONSTRAINTS
    deploy:
      resources:
        limits:
          cpus: "2.0" # Max 2 CPU cores
          memory: 512M # Max 512MB RAM
        reservations:
          cpus: "1.0" # Guaranteed 1 CPU core
          memory: 256M # Guaranteed 256MB RAM
    mem_swappiness: 10 # Reduce swap usage
    pids_limit: 1000 # Increased for more goroutines
    ulimits:
      nofile:
        soft: 200000 # Support 20k+ connections with available RAM
        hard: 200000
      nproc:
        soft: 32768 # More threads
        hard: 32768
    blkio_config:
      weight: 500 # Disk I/O weight (100-1000)

  publisher:
    build:
      context: .
      dockerfile: Dockerfile.publisher
    container_name: odin-publisher
    ports:
      - "3003:3003" # HTTP control API
    environment:
      - NATS_URL=nats://nats:4222
      - NODE_ENV=production
    networks:
      - odin-network
    depends_on:
      nats:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
        reservations:
          cpus: "0.25"
          memory: 64M

networks:
  odin-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450 # Optimize for containers

volumes:
  nats_data:
