version: '3'

# Main Taskfile - Orchestrates all sub-taskfiles
# Run 'task --list' to see all available tasks

includes:
  build:
    taskfile: ./taskfiles/build.yml
    dir: .
  docker:
    taskfile: ./taskfiles/docker.yml
    dir: .
  dev:
    taskfile: ./taskfiles/dev.yml
    dir: .
  test:
    taskfile: ./taskfiles/test.yml
    dir: .
  monitor:
    taskfile: ./taskfiles/monitor.yml
    dir: .
  publisher:
    taskfile: ./taskfiles/publisher.yml
    dir: .
  utils:
    taskfile: ./taskfiles/utils.yml
    dir: .
  gcp:
    taskfile: ./taskfiles/deploy-gcp.yml
    dir: .

# === COMBINED WORKFLOWS ===
# Common task combinations for quick access

tasks:
  default:
    desc: Show available task categories
    cmds:
      - echo "📋 Available task categories:"
      - echo ""
      - echo "  build:*      - Build Go server and TypeScript publisher"
      - echo "  docker:*     - Docker container management"
      - echo "  dev:*        - Local development tasks"
      - echo "  test:*       - Stress testing and load testing"
      - echo "  monitor:*    - Health checks and monitoring"
      - echo "  publisher:*  - Publisher control (start/stop/configure)"
      - echo "  utils:*      - Install, format, clean utilities"
      - echo "  gcp:*        - GCP deployment and management"
      - echo ""
      - echo "  setup        - Complete local setup (install → build → start)"
      - echo "  quick-start  - Quick start for testing (docker:up → test:light)"
      - echo "  full-test    - Full test workflow (docker:up → test:medium → stats)"
      - echo ""
      - echo "Run 'task --list-all' to see all available tasks"

  setup:
    desc: Complete setup (install → build → start)
    cmds:
      - task: utils:install
      - task: build:docker
      - task: docker:up

  quick-start:
    desc: Quick start for testing (docker:up → test:light)
    cmds:
      - task: docker:up
      - sleep 5
      - task: test:light

  full-test:
    desc: Full test workflow (docker:up → test:medium → stats)
    cmds:
      - task: docker:up
      - sleep 5
      - task: test:medium
      - task: monitor:health
      - task: monitor:publisher:stats
