# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

includes:
  test: ./tasks/test.yml

vars:
  NODE_SERVER_PORT: "3001"
  GO_SERVER_PORT: "3002"
  GO3_SERVER_PORT: "3005"
  PUBLISHER_PORT: "3003"
  NATS_PORT: "4222"
  NATS_MONITOR_PORT: "8222"

tasks:
  dev:
    desc: "🚀 Start dev environment for go-server-2"
    cmds:
      - echo "🐳 Starting dev stack (NATS + Go-2 + Publisher)..."
      - docker-compose up -d --build nats ws-go-2 publisher
      - echo "✅ Dev stack ready!"
      - echo "  🔌 WebSocket at ws://localhost:3004/ws"

  # Main entry points - containerized services
  start:
    desc: "🚀 Start complete containerized stack (NATS + Node.js + Go + Publisher)"
    cmds:
      - echo "🐳 Starting complete containerized stack..."
      - docker-compose up -d
      - sleep 10
      - echo "▶️  Starting publisher with live price data..."
      - task: publisher:start
      - echo "✅ All services ready!"
      - echo ""
      - echo "Services:"
      - echo "  🔌 Node.js WebSocket at ws://localhost:3001/ws"
      - echo "  ⚡ Go WebSocket at ws://localhost:3002/ws (original)"
      - echo "  ⚡ Go-2 WebSocket at ws://localhost:3004/ws (optimized)"
      - echo "  🚀 Go-3 WebSocket at ws://localhost:3005/ws (next-gen)"
      - echo "  🎛️  Publisher Control at http://localhost:3003/control"
      - echo "  📊 NATS Monitor at http://localhost:8222"

  start:node:
    desc: "🟢 Start Node.js stack only (NATS + Node.js + Publisher)"
    cmds:
      - echo "🐳 Starting Node.js stack..."
      - docker-compose up -d nats ws-node publisher
      - sleep 5
      # - echo "▶️  Starting publisher with live price data..."
      # - task: publisher:start
      - echo "✅ Node.js stack ready!"
      - echo "  🔌 WebSocket at ws://localhost:3001/ws"

  start:go:
    desc: "⚡ Start Go stack only (NATS + Go-2 + Publisher)"
    cmds:
      - echo "🐳 Starting Go-2 stack..."
      - docker-compose up -d nats ws-go-2 publisher
      - sleep 5
      # - echo "▶️  Starting publisher with live price data..."
      # - task: publisher:start
      - echo "✅ Go-2 stack ready!"
      - echo "  🔌 WebSocket at ws://localhost:3004/ws"

  start:go3:
    desc: "🚀 Start Go-3 stack only (NATS + Go-3 + Publisher)"
    cmds:
      - echo "🐳 Starting Go-3 stack..."
      - docker-compose up -d nats ws-go-3 publisher
      - sleep 5
      # - echo "▶️  Starting publisher with live price data..."
      # - task: publisher:start
      - echo "✅ Go-3 stack ready!"
      - echo "  🚀 WebSocket at ws://localhost:3005/ws"

  # Publisher control
  publisher:start:
    desc: "▶️  Start publisher stress test"
    cmds:
      - |
        curl -s -X POST http://localhost:3003/control \
          -H "Content-Type: application/json" \
          -d '{"action": "start", "messagesPerSecond": 50, "connections": 100}' \
          | jq .

  publisher:stop:
    desc: "⏹️  Stop publisher"
    cmds:
      - |
        curl -s -X POST http://localhost:3003/control \
          -H "Content-Type: application/json" \
          -d '{"action": "stop"}' \
          | jq .

  publisher:stats:
    desc: "📊 Show publisher statistics"
    cmds:
      - curl -s http://localhost:3003/stats | jq .

  # Health and status checks
  status:
    desc: "📊 Check status of all services"
    cmds:
      - echo "📊 Service Status Check"
      - echo "======================="
      - echo ""
      - echo "🐳 Docker Containers:"
      - docker-compose ps
      - echo ""
      - echo "🏥 Health Checks:"
      - |
        if curl -s http://localhost:3001/health > /dev/null; then
          echo "  ✅ Node.js server healthy"
        else
          echo "  ❌ Node.js server not healthy"
        fi
      - |
        if curl -s http://localhost:3002/health > /dev/null; then
          echo "  ✅ Go server (original) healthy"
        else
          echo "  ❌ Go server (original) not healthy"
        fi
      - |
        if curl -s http://localhost:3004/health > /dev/null; then
          echo "  ✅ Go-2 server (optimized) healthy"
        else
          echo "  ❌ Go-2 server (optimized) not healthy"
        fi
      - |
        if curl -s http://localhost:3003/health > /dev/null; then
          echo "  ✅ Publisher healthy"
        else
          echo "  ❌ Publisher not healthy"
        fi

  logs:
    desc: "📜 Show logs from all services"
    cmds:
      - docker-compose logs --tail=20

  logs:node:
    desc: "📜 Show Node.js server logs"
    cmds:
      - docker-compose logs -f ws-node

  logs:go:
    desc: "📜 Show Go server logs"
    cmds:
      - docker-compose logs -f ws-go-2

  logs:publisher:
    desc: "📜 Show publisher logs"
    cmds:
      - docker-compose logs -f publisher

  # Build and rebuild
  build:
    desc: "🔨 Build all containers"
    cmds:
      - echo "🔨 Building all containers..."
      - docker-compose build
      - echo "✅ All containers built"

  rebuild:
    desc: "🔄 Rebuild and restart all services"
    cmds:
      - echo "🔄 Rebuilding and restarting..."
      - task: stop
      - docker-compose build
      - task: start

  rebuild:node:
    desc: "🔄 Rebuild and restart Node.js service"
    cmds:
      - docker-compose stop ws-node
      - docker-compose build ws-node
      - docker-compose up -d ws-node

  rebuild:go:
    desc: "🔄 Rebuild and restart Go service"
    cmds:
      - docker-compose stop ws-go-2
      - docker-compose build ws-go-2
      - docker-compose up -d ws-go-2

  # Testing
  test:quick:
    desc: "🧪 Quick connectivity test"
    cmds:
      - task: test:connectivity

  test:stress:
    desc: "🧪 Run stress test using publisher control API"
    cmds:
      - echo "🧪 Starting 30-second stress test..."
      - task: publisher:start
      - sleep 30
      - task: publisher:stop
      - echo "📊 Final stats:"
      - task: publisher:stats

  # WebSocket connection stress tests
  stress:go:
    desc: "🧪 Stress test Go WebSocket server with multiple connections"
    cmds:
      - echo "🧪 Stress testing Go server..."
      - node stress-test-go.cjs {{.CLI_ARGS | default "50 30"}}

  stress:node:
    desc: "🧪 Stress test Node.js WebSocket server with multiple connections"
    cmds:
      - echo "🧪 Stress testing Node.js server..."
      - node stress-test-node.cjs {{.CLI_ARGS | default "50 30"}}

  stress:both:
    desc: "🧪 Stress test both WebSocket servers simultaneously"
    cmds:
      - echo "🧪 Starting stress test on both servers..."
      - task: publisher:start
      - echo "Starting WebSocket clients..."
      - |
        (node stress-test-go.cjs {{.CLI_ARGS | default "25 30"}} &)
        (node stress-test-node.cjs {{.CLI_ARGS | default "25 30"}} &)
        wait
      - task: publisher:stop

  stress:only:
    desc: "🚀 Launch stress test suite (assumes services already running)"
    cmds:
      - echo "🚀 Launching stress test suite..."
      - echo "📊 Running parallel stress tests ({{.CLI_ARGS | default "100 60"}})..."
      - |
        ARGS="{{.CLI_ARGS | default "100 60"}}"
        CONNECTIONS=$(echo $ARGS | cut -d' ' -f1)
        DURATION=$(echo $ARGS | cut -d' ' -f2)
        HALF_CONNECTIONS=$((CONNECTIONS / 2))

        echo "🎯 Test Configuration:"
        echo "  Total Connections: $CONNECTIONS ($HALF_CONNECTIONS per server)"
        echo "  Duration: ${DURATION}s"
        echo ""

        (node stress-test-node.cjs $HALF_CONNECTIONS $DURATION &)
        # (node stress-test-go.cjs $HALF_CONNECTIONS $DURATION &)
        # (node stress-test-high-load.cjs $HALF_CONNECTIONS $DURATION &)
        wait
      - echo ""
      - echo "✅ Stress test completed!"

  stress:stop:
    desc: "🛑 Stop running stress tests"
    cmds:
      - echo "🛑 Stopping stress tests..."
      - |
        echo "Killing Node.js stress test processes..."
        pkill -f "stress-test" || echo "No stress test processes found"
        echo "✅ Stress tests stopped"

  stress:container:
    desc: "🧪 Container-optimized stress test for Go-2 server (512MB/2CPU limits)"
    cmds:
      - echo "🧪 Running Go-2 container-optimized stress test..."
      - |
        echo "🎯 Container Test Configuration:"
        echo "  Go Server 2: Targeting 5000 connections (512MB limit)"
        echo "  Duration: 60 seconds"
        echo ""
        echo "🔥 Testing Go server 2 (container optimized - port 3004)..."
        node stress-test-high-load.cjs 5000 60 go2
      - echo ""
      - echo "✅ Container stress test completed!"

  test:connection-rate:
    desc: "🧪 Test Go-2 server connection success rate (target: 90%+)"
    cmds:
      - echo "🧪 Testing Go-2 server connection rate..."
      - |
        echo "🎯 Connection Rate Test:"
        echo "  Target: 90%+ success rate"
        echo "  Go-2 server: 3000 connections"
        echo ""
        node test-connection-rate.cjs ws://localhost:3004/ws 3000
      - echo ""
      - echo "✅ Connection rate test completed!"

  # Cleanup
  stop:
    desc: "🛑 Stop all services"
    cmds:
      - echo "🛑 Stopping all services..."
      - docker-compose down
      - echo "✅ All services stopped"

  clean:
    desc: "🧹 Clean up everything (containers, images, volumes)"
    cmds:
      - echo "🧹 Cleaning up..."
      - docker-compose down -v --remove-orphans
      - docker system prune -f --volumes
      - echo "✅ Cleanup complete"

  # Development helpers
  shell:node:
    desc: "🐚 Open shell in Node.js container"
    cmds:
      - docker-compose exec ws-node sh

  shell:go:
    desc: "🐚 Open shell in Go container"
    cmds:
      - docker-compose exec ws-go-2 sh

  # Help
  default:
    desc: "🏠 Show main commands"
    cmds:
      - task: help

  help:
    desc: "📖 Show available commands"
    silent: true
    cmds:
      - echo "🚀 WebSocket Performance Testing Stack"
      - echo "======================================"
      - echo ""
      - echo "📦 Main Commands:"
      - echo "  task start          - Start complete stack (recommended)"
      - echo "  task start:node     - Start Node.js stack only"
      - echo "  task start:go       - Start Go stack only"
      - echo "  task stop           - Stop all services"
      - echo ""
      - echo "🧪 Testing:"
      - echo "  task test:quick     - Quick connectivity test"
      - echo "  task test:stress    - Stress test with publisher"
      - echo "  task test:compare   - Compare Node.js vs Go performance"
      - echo ""
      - echo "📊 Monitoring:"
      - echo "  task status         - Check all services"
      - echo "  task logs           - View all logs"
      - echo "  task publisher:stats - Publisher metrics"
      - echo ""
      - echo "🛠️  Development:"
      - echo "  task build          - Build all containers"
      - echo "  task rebuild        - Rebuild and restart"
      - echo "  task clean          - Clean up everything"
      - echo ""
      - echo "🔗 URLs (after starting):"
      - echo "  Node.js WS at ws://localhost:3001/ws"
      - echo "  Go WS (original) at ws://localhost:3002/ws"
      - echo "  Go-2 WS (optimized) at ws://localhost:3004/ws"
      - echo "  Publisher API at http://localhost:3003"
      - echo "  NATS Monitor at http://localhost:8222"