version: '3'

includes:
  nats: ./tasks/nats.yml
  node: ./tasks/nodejs.yml
  go: ./tasks/go.yml
  test: ./tasks/test.yml

vars:
  NODE_SERVER_PORT: "3001"
  GO_SERVER_PORT: "3002"
  NATS_PORT: "4222"
  NATS_MONITOR_PORT: "8222"

tasks:
  # Quick start commands - the main entry points
  start:
    desc: "🚀 Start complete Node.js stack (NATS + Server + Publisher) - Containerized"
    cmds:
      - echo "🐳 Starting containerized Node.js stack..."
      - docker-compose up -d nats ws-node publisher
      - sleep 5
      - echo "✅ Node.js stack ready!"
      - echo "🔌 WebSocket at ws://localhost:{{.NODE_SERVER_PORT}}/ws"
      - echo "📊 Dashboard at http://localhost:{{.NODE_SERVER_PORT}}/dashboard"
      - echo "📊 Container resources - 512MB RAM, 2 CPU cores"

  start:go:
    desc: "⚡ Start complete Go stack (NATS + Go Server + Publisher) - Containerized"
    cmds:
      - echo "🐳 Starting containerized Go stack..."
      - docker-compose up -d nats ws-go publisher
      - sleep 5
      - echo "✅ Go stack ready!"
      - echo "📈 Stats API at http://localhost:{{.GO_SERVER_PORT}}/stats"
      - echo "🔌 WebSocket at ws://localhost:{{.GO_SERVER_PORT}}/ws"




  # Testing workflows
  test:
    desc: "🧪 Run quick load test on active server"
    cmds:
      - task: test:quick

  test:all:
    desc: "🧪 Run comprehensive performance comparison"
    cmds:
      - task: test:compare:performance

  # Utility commands
  stop:
    desc: "🛑 Stop all running services (containers and host processes)"
    cmds:
      - echo "🛑 Stopping containers..."
      - docker-compose down || true
      - echo "🛑 Stopping host processes..."
      - task: nats:stop
      - pkill -f "tsx src" || true
      - pkill -f "odin-ws-server" || true
      - pkill -f "python3 -m http.server" || true
      - echo "✅ All services stopped (containers and host processes)"

  clean:
    desc: "🧹 Clean up build artifacts and stop services"
    cmds:
      - task: stop
      - task: go:clean
      - echo "✅ Cleanup complete"

  default:
    desc: "🏠 Default task - show help"
    cmds:
      - task: help