# Backend Services - Isolated Setup
# Instance: odin-backend (e2-small)
# Services: NATS, Publisher, Prometheus, Grafana, Loki, Promtail
#
# NATS is exposed on 0.0.0.0:4222 to allow ws-go instance to connect via internal network

services:
  nats:
    image: nats:2.12-alpine
    container_name: odin-nats
    ports:
      - "0.0.0.0:4222:4222"    # Exposed for remote ws-go connection
      - "127.0.0.1:8222:8222"  # Monitoring (local only)
    command:
      - "--jetstream"
      - "--store_dir=/data"
      - "--http_port=8222"
    volumes:
      - nats_data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  publisher:
    build:
      context: ./publisher
      dockerfile: Dockerfile
    container_name: odin-publisher
    ports:
      - "0.0.0.0:3003:3003"
    environment:
      - NATS_URL=nats://nats:4222
      - PORT=3003
    depends_on:
      - nats
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 128M

  prometheus:
    image: prom/prometheus:v3.6.0
    container_name: odin-prometheus
    ports:
      - "127.0.0.1:9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=7d"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 256M

  grafana:
    image: grafana/grafana:12.2.0
    container_name: odin-grafana
    ports:
      - "0.0.0.0:3010:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 512M

  loki:
    image: grafana/loki:3.3.2
    container_name: odin-loki
    ports:
      - "0.0.0.0:3100:3100"  # Exposed for remote Promtail (ws-go instance)
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
      - loki_data:/loki
    command: -config.file=/etc/loki/loki-config.yml
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 256M

  promtail:
    image: grafana/promtail:3.3.2
    container_name: odin-promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 128M

volumes:
  nats_data:
  prometheus_data:
  grafana_data:
  loki_data:
