version: '3'

# Build tasks for Go server and TypeScript publisher

vars:
  GO_SERVER_DIR: ../src
  PUBLISHER_DIR: ../publisher

tasks:
  go:
    desc: Build Go server binary locally
    dir: "{{.GO_SERVER_DIR}}"
    cmds:
      - go build -o server .
    sources:
      - "*.go"
      - go.mod
      - go.sum

  publisher:
    desc: Compile TypeScript publisher
    dir: "{{.PUBLISHER_DIR}}"
    cmds:
      - npm run build
    sources:
      - "*.ts"
      - "config/**/*.ts"
      - "types/**/*.ts"
      - tsconfig.json

  docker:
    desc: Build all Docker images
    cmds:
      - task: docker:go
      - task: docker:publisher

  docker:go:
    desc: Build Go server Docker image
    cmds:
      - docker compose build ws-go

  docker:publisher:
    desc: Build publisher Docker image
    cmds:
      - docker compose build publisher

  all:
    desc: Build everything (local + Docker)
    cmds:
      - task: go
      - task: publisher
      - task: docker
