version: '3'

# Development tasks for running services locally

vars:
  GO_SERVER_DIR: ../src
  PUBLISHER_DIR: ../publisher

tasks:
  go:
    desc: Run Go server locally (outside Docker)
    dir: "{{.GO_SERVER_DIR}}"
    cmds:
      - go run . -addr=:3002 -nats=nats://localhost:4222

  publisher:
    desc: Run publisher locally
    dir: "{{.PUBLISHER_DIR}}"
    cmds:
      - npm run dev

  nats:
    desc: Start only NATS container for local development
    cmds:
      - docker compose up -d nats
      - echo "✅ NATS started on nats://localhost:4222"
